### PR TITLE
Implements #127

### PR DESCRIPTION
**Pull request by dwclark**

### CODE REVIEW

**Comment by dwclark** [comment]
No rush on merging this. I am going to try and close out support for proxy connections soon too.

**Comment by cjstehno** [comment]
What, no tests? Other than that it looks good to me. I created a [separate issue](https://github.com/http-builder-ng/http-builder-ng/issues/131) to update the user guide - I can do that. I will also add a test or two then.

**Comment by dwclark** [comment]
I'll add some tests today.

**Comment by dwclark** [comment]
OK, tests added

**Pull request merged**
