### PR TITLE
Travis-ci configuration

### PR DESCRIPTION
**Pull request by aalmiray**
Instructions for enabling Travis to make a new build:
1. Log into  https://travis-ci.org/ using your GitHub account.
2. Locate the '+' on the left sidebar next to "My repositories".
3. Find "dwclark/http-builder-ng" and activate it.

### CODE REVIEW

**Comment by aalmiray** [comment]
Fix for #28

**Comment by cjstehno** [comment]
Looks like I might have permissions to do this now - I will give it a try over the long weekend.

**Comment by cjstehno** [comment]
Bah! I still don't - I have an email out to Dave about creating a GitHub Organization for the project or getting this stuff setup.

**Comment by cjstehno** [comment]
Ok, I have the permissions I need on the new organization - I have pulled your changes into a branch and am testing them. Thanks for the intro to Travis!

**Comment by aalmiray** [comment]
For future reference, should PRs be sent to the `development` branch?

**Comment by cjstehno** [comment]
Yes, please. Though we are not sticklers about it - if it's a quick (or important) bug fix, going to `master` is ok. I should probably write up a contribution document.

**Comment by aalmiray** [comment]
Sorry, my mistake. I did not notice the `development` branch early on. Following PRs will target `development` unless there's a critical thing to fix in `master` 😏

**Pull request closed without merging**
