### PR TITLE
Support for traverse() when looking for useRawValues.

### PR DESCRIPTION
**Pull request by PredatorVI**
These changes work for my use case allowing the correct value for useRawValues to be found in the UriBuilder chain.

### CODE REVIEW

**Comment by PredatorVI** [comment]
@cjstehno I think this fixes my use case on top of the fix you made.  I hope I didn't do something wrong to cause the conflict above.

**Comment by cjstehno** [comment]
Does this actually fix your issue?

**Comment by PredatorVI** [comment]
Yes it does.

**Comment by cjstehno** [comment]
Ok, I will give it a try.

**Comment by cjstehno** [comment]
I just added your implementation into the development branch directly and the tests still pass. If you can, try pulling down the `development` branch and making sure that it still solves your problem.

**Pull request closed without merging**
